# Generated by Django 3.0.2 on 2020-05-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200524_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Man'), (2, 'Woman'), (3, 'Other')]),
        ),
    ]
