# Generated by Django 3.0.2 on 2020-05-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200524_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Teacher'), (2, 'Student')], null=True),
        ),
    ]
