# Generated by Django 3.0.2 on 2020-05-24 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, choices=[(1, 'Shou4'), (2, 'Shou5'), (3, 'Shou6'), (4, 'Chu1'), (5, 'Chu2'), (6, 'Chu3'), (7, 'Kou1'), (8, 'Kou2'), (9, 'Kou3')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
