# Generated by Django 3.0.2 on 2020-05-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.TextField(blank=True, choices=[('小学4年生', 'Shou4'), ('小学5年生', 'Shou5'), ('小学6年生', 'Shou6'), ('中学1年生', 'Chu1'), ('中学2年生', 'Chu2'), ('中学3年生', 'Chu3'), ('高校1年生', 'Kou1'), ('高校2年生', 'Kou2'), ('高校3年生', 'Kou3')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
