# Generated by Django 3.0.2 on 2020-05-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200524_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.TextField(blank=True, choices=[('小学4年生', '小学4年生'), ('小学5年生', '小学5年生'), ('小学6年生', '小学6年生'), ('中学1年生', '中学1年生'), ('中学2年生', '中学2年生'), ('中学3年生', '中学3年生'), ('高校1年生', '高校1年生'), ('高校2年生', '高校2年生'), ('高校3年生', '高校3年生')], max_length=10, null=True),
        ),
    ]
