# Generated by Django 3.0.2 on 2020-05-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200524_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, choices=[('sj', '中受国語'), ('sm', '中受算数'), ('ce', '中学英語'), ('cm', '中学数学'), ('kk', '高校古文'), ('kg', '高校現代文'), ('m1', '高校数学I'), ('ma', '高校数学A'), ('m2', '高校数学II'), ('mb', '高校数学B'), ('ke', '高校英語')], default='cm', max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.TextField(blank=True, choices=[('s4', '小学4年生'), ('s5', '小学5年生'), ('s6', '小学6年生'), ('c1', '中学1年生'), ('c2', '中学2年生'), ('c3', '中学3年生'), ('k1', '高校1年生'), ('k2', '高校2年生'), ('k3', '高校3年生')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kamoku',
            field=models.ManyToManyField(blank=True, null=True, to='account.Subject'),
        ),
    ]
