# Generated by Django 3.0.2 on 2020-05-24 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdate', models.DateField()),
                ('worktime', models.TextField(choices=[('c1', '14:00'), ('c2', '15:00'), ('c3', '16:00'), ('c4', '17:00'), ('c5', '18:00'), ('c6', '19:00'), ('c7', '20:00'), ('c8', '21:00'), ('c9', '22:00')], default='c5', max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReserveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, choices=[('sj', '中受国語'), ('sm', '中受算数'), ('ce', '中学英語'), ('cm', '中学数学'), ('kk', '高校古文'), ('kg', '高校現代文'), ('m1', '高校数学I'), ('ma', '高校数学A'), ('m2', '高校数学II'), ('mb', '高校数学B'), ('ke', '高校英語')], default='cm', max_length=10, null=True)),
                ('textbook', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
