# Generated by Django 3.0.2 on 2020-05-24 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodel',
            name='reservedate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservemodel',
            name='reservetime',
            field=models.TextField(choices=[('c1', '14:00'), ('c2', '15:00'), ('c3', '16:00'), ('c4', '17:00'), ('c5', '18:00'), ('c6', '19:00'), ('c7', '20:00'), ('c8', '21:00'), ('c9', '22:00')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
