# Generated by Django 3.0.2 on 2020-05-24 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20200524_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodel',
            name='student',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
