# Generated by Django 3.0.2 on 2020-05-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservemodel_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservemodel',
            name='studentid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
